root: ./

​structure:  
  readme: README.md  
  summary: SUMMARY.md​

redirects:
  test: /getting-started/hello-world-using-curl.md
  getting-started/hello-world-postman: /getting-started/hello-world-using-curl.md
