root: ./

​structure:  
    readme: README.md  
    summary: SUMMARY.md​
    
redirects:  
    docs/guides/getting-started/hello-world-postman: https://shotstack.io/docs/guide/getting-started/hello-world-postman